### PR TITLE
General code quality fix-2

### PR DESCRIPTION
**Pull request by faisal-hameed**
This pull request is focused on resolving occurrences of Sonar rules 
squid:S1155 - Collection.isEmpty() should be used to test for emptiness. 
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S2147 - Catches should be combined.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:S2147

Please let me know if you have any questions.

Faisal Hameed

### CODE REVIEW

**Comment by nrlakin** [comment]
Close/reopen to force travis-ci build.

**Comment by faisal-hameed** [comment]
@nrlakin It looks like there is an issue in travis configuration. 
https://travis-ci.org/ResearchStack/ResearchStack/builds/133513442

**Comment by nrlakin** [comment]
It builds on the main branch, but Travis appears to be inconsistent in loading the config file if it doesn't exist in the pull request branch. Try merging and updating the pull request.

**Comment by faisal-hameed** [comment]
I don't have rights to merge pull requests.

**Comment by nrlakin** [comment]
You don't need to merge, just update the pull request. Checkout the corresponding branch, pull from the upstream master (ResearchStack), then commit and push to DevFactory:release/general-code-quality-fix-2. There shouldn't be merge conflicts. It's an issue with Travis CI, it isn't finding the .travis.yml file in your branch because it didn't exist when you forked.

**Comment by faisal-hameed** [comment]
@nrlakin Ok, I will rebase my branches from master.

**Comment by faisal-hameed** [comment]
@nrlakin Done.

**Comment by nrlakin** [comment]
@faisal-hameed Thank you, I will be dealing with outstanding pull requests in the coming days. Sorry for the hassle, should be a one-time migration issue.

**Comment by mikecarroll** [comment]
Yes, many apologies for the hassle, @faisal-hameed -- we are still getting our act together with best practices on running this as a community-driven project. Deeply appreciate your contributions!

**Pull request merged**
