### PR TITLE
Issues/nopp improvements

### PR DESCRIPTION
**Pull request by dukemike**

### CODE REVIEW

**Comment by dukemike** [comment]
Sorry, picked wrong pull request destination.

**Comment by crayne** [comment]
I'm confused -- why are these things being merged before the outstanding pull requests?

**Comment by dukemike** [comment]
Nothing should have been merged. I created the pull request improperly so I closed it. I didn't see a magical "delete pull request" button :)

**Comment by crayne** [comment]
Got it.  Sorry for the misunderstanding.

**Comment by mikecarroll** [comment]
@dukemike No worries! I think we've all gotten remotes confused before.

@crayne Almost past the bottleneck with merging PRs on this end. Sorry about the delays.

**Comment by mikecarroll** [comment]
And would love to see some of your work/improvements to the core platform in a future PR, @anitadesai !

**Pull request closed without merging**
